# Programming Assignment 2
# Casiedo, Jihan Harvey C.
# 2ECE-A
# Normalization Problem

In [7]:
import numpy as np #import numpy

X = np.random.rand(5,5) #create the 5x5 matrix

mean = X.mean() #calculate the mean
std = X.std() #calculate the standard deviation

X_normalized = (X - mean) / std #normalization formula

np.save('X_normalized.npy', X_normalized) #save the array

print("Original array (X):\n", X) #print the values
print("\nNormalized array (X_normalized): \n", X_normalized)

Original array (X):
 [[0.47173961 0.87388228 0.5048641  0.10224272 0.62413114]
 [0.47406068 0.62044332 0.88389703 0.2294866  0.82331755]
 [0.43812507 0.89924874 0.07728921 0.10754016 0.66728962]
 [0.20300247 0.13477157 0.11911956 0.43440738 0.02953826]
 [0.96367134 0.88587779 0.24222815 0.04504613 0.76273884]]

Normalized array (X_normalized): 
 [[ 0.02244703  1.30810494  0.12834667 -1.15884169  0.5096457 ]
 [ 0.02986753  0.49785569  1.34012228 -0.75204053  1.14644853]
 [-0.08501929  1.389202   -1.23861853 -1.14190565  0.6476242 ]
 [-0.83671082 -1.05484633 -1.10488611 -0.09690482 -1.39127927]
 [ 1.5951623   1.34645482 -0.71130555 -1.3417003   0.95277721]]


# Division by 3 Problem

In [24]:
import numpy as np #import numpy

X = np.arange(1, 101).reshape(10, 10) #use arrange to create 1-100 values and use reshape to make into 2D 10x10 matrix

div_by_3 = X[X % 3 == 0] #selects the values that are divisible by 3 using modulo operation

np.save('div_by_3.npy', div_by_3) #save the array

print ("Original matrix: \n", X) #print the values
print ("\nNumbers divisible by 3 from 1-100 are: \n", div_by_3)

Original matrix: 
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Numbers divisible by 3 from 1-100 are: 
 [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
